version: "3.9"

services:
  ecommerce-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong!Pass123"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network

  ecommerce-webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-webapi
    depends_on:
      - ecommerce-sqlserver
      - ecommerce-redis
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      MSSQL_SA_USER: sa
      MSSQL_SA_PASSWORD: Strong!Pass123   
    command: ["./wait-for-sql.sh", "ecommerce-sqlserver", "dotnet", "EcommerceWebApi.dll"]
    ports:
      - "5208:80"
    volumes:
      - product-images:/app/wwwroot/images
    networks:
      - app-network

  ecommerce-redis:
    image: redis:latest
    container_name: ecommerce-redis
    deploy:
      resources:
        limits:
          memory: 4gb # redis total cache limit
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  sqlserver-data:
  product-images:
  redis-data:

networks:
  app-network:
    driver: bridge
