version: "3.9"

services:
  dockersqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dockersqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong!Pass123"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerceapi
    depends_on:
      - dockersqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      # ConnectionStrings__DefaultConnection: Server=dockersqlserver;Database=EcommerceWebApiDb;User Id=sa;Password=Strong!Pass123;
      MSSQL_SA_USER: sa
      MSSQL_SA_PASSWORD: Strong!Pass123   
    command: ["./wait-for-sql.sh", "dockersqlserver", "dotnet", "EcommerceWebApi.dll"]
    ports:
      - "5208:80"
    volumes:
      - product-images:/app/wwwroot/images
    networks:
      - app-network

volumes:
  sqlserver-data:
  product-images:

networks:
  app-network:
    driver: bridge
